name: Test, ensure formatted, and verify README examples

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gleam: [0.12.1, 0.13.2, 0.14.0]
    steps:
      - uses: actions/checkout@v2.0.0

      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 23.2
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: ${{ matrix.gleam }}
      - run: rebar3 install_deps
      - name: Run Gleam tests
        run: rebar3 eunit
      - run: gleam format --check src test

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g codedown
      - name: Verify that Gleam code in README compiles
        run: |
          cat README.md | codedown rust > src/readme.gleam
          gleam build
